### ISSUE TITLE
AOE / Splash Damage / Damage rework / enhancement

### ISSUE THREAD

**Issue by cmr624** [elliot-winch/ProcJam2018#10]
Splash Damage data (radius) this is *ADDITIONAL DAMAGE* tied to the time of explosion. 

And the impact damage should be proportional to the velocity AT IMPACT and each PGF has a different modifier / scalar for that ratio. 

We need a proportional ratio of velocity to damage. be able to weight the impact velocity to have control over the variable.

basically, rework of the damage dropoff variable in some way

but also, the AOE just needs to be implemented with the radius system discussed (at point of impact, determine a radius of explosion, and set how far you are from it, and based on some formula determine how much damage you take)

bring on the gaussian ;)

**Comment by elliot-winch** [comment]
Done
